(defun split-string (s delim)
  (do* ((i 0 (1+ j)) 
        (j (position delim s)
           (position delim s :start i))
        (sub (subseq s i j) (subseq s i j))
        (L (when (string-not-equal "" sub) (list sub))
           (if (string-not-equal "" sub) 
               (cons (subseq s i j) L)
               L)))
       ((not j) (reverse L))))

(defun main (args)
  (let ((pathstr (if (>= (length args) 2)
                  (second args)
                  (read-line)))) 
    (dolist (path (split-string pathstr #\:))
      (print path))
   (format t "~%")))
